export const cities = [
    {
        id:1,
        value:'tashkent',
        name:'Ташкент',
    },
    {
        id:2,
        value:'andijan',
        name:'Андиджан',
    },
    {
        id:3,
        value:'bukhara',
        name:'Бухара',
    },
    {
        id:4,
        value:'jizzakh',
        name:'Джизак',
    },
    {
        id:5,
        value:'karshi',
        name:'Карши',
    },
    {
        id:6,
        value:'navoi',
        name:'Навои',
    },
    {
        id:7,
        value:'namangan',
        name:'Наманган',
    },
    {
        id:8,
        value:'nukus',
        name:'Нукус',
    },
    {
        id:9,
        value:'termez',
        name:'Термез',
    },
    {
        id:10,
        value:'urgench',
        name:'Ургенч',
    },
    {
        id:11,
        value:'abu dahbi',
        name:'Абу-Даби',
    },
    {
        id:12,
        value:'astana',
        name:'Аддис-Абеба',
    },
    {
        id:13,
        value:'bishkek',
        name:'Алжир',
    },
    {
        id:14,
        value:'amman',
        name:'Амман',
    },
    {
        id:15,
        value:'amsterdam',
        name:'Амстердам',
    },
    {
        id:16,
        value:'ankara',
        name:'Анкаpа',
    },
    {
        id:17,
        value:'antananarivo',
        name:'Антананариву',
    },
    {
        id:18,
        value:'afina',
        name:'Афины',
    },
    {
        id:19,
        value:'ashgabat',
        name:'Ашхабад',
    },
    
    {
        id:20,
        value:'bagdad',
        name:'Багдад',
    },
    {
        id:21,
        value:'baku',
        name:'Баку',
    },
    {
        id:22,
        value:'bangkok',
        name:'Бангкок',
    },
    {
        id:23,
        value:'beyrut',
        name:'Бейрут',
    },
    {
        id:24,
        value:'belgrad',
        name:'Белград',
    },
    {
        id:25,
        value:'berlin',
        name:'Берлин',
    },
    {
        id:26,
        value:'bishkek',
        name:'Бишкек',
    },
    {
        id:27,
        value:'bogota',
        name:'Богота',
    },
    {
        id:28,
        value:'brazilia',
        name:'Бразилиа',
    },
    {
        id:29,
        value:'bratislava',
        name:'Братислава',
    },
    {
        id:30,
        value:'brussels',
        name:'Брюссель',
    },
    {
        id:31,
        value:'budapest',
        name:'Будапешт',
    },
    {
        id:32,
        value:'bucharest',
        name:'Бухарест',
    },
    {
        id:33,
        value:'Buenos Aires',
        name:'Буэнос-Айрес',
    },
    {
        id:34,
        value:'warsaw',
        name:'Варшава',
    },
    {
        id:35,
        value:'vatikan',
        name:'Ватикан',
    },
    {
        id:36,
        value:'washington',
        name:'Вашингтон',
    },
    {
        id:37,
        value:'vena',
        name:'Вена',
    },
    {
        id:38,
        value:'havana',
        name:'Гавана',
    },
    {
        id:39,
        value:'guatemala',
        name:'Гватемала',
    },
    {
        id:40,
        value:'damask',
        name:'Дамаск',
    },
    {
        id:41,
        value:'deli',
        name:'Дели',
    },
    {
        id:42,
        value:'beruni',
        name:'Беруни',
    },
    {
        id:43,
        value:'doha',
        name:'Доха',
    },
    {
        id:44,
        value:'dublin',
        name:'Дублин',
    },
    {
        id:45,
        value:'dushanbe',
        name:'Душанбе',
    },
    {
        id:46,
        value:'erevan',
        name:'Ереван',
    },
    {
        id:47,
        value:'zagreb',
        name:'Загреб',
    },
    {
        id:48,
        value:'islamabad',
        name:'Исламабад',
    },
    {
        id:49,
        value:'Jerusalem',
        name:'Иерусалим',
    },
    {
        id:50,
        value:'cairo',
        name:'Каир',
    },
    {
        id:51,
        value:'kabul',
        name:'Кабул',
    },
    {
        id:52,
        value:'damask',
        name:'Дамаск',
    },
    {
        id:53,
        value:'deli',
        name:'Дели',
    },
    {
        id:54,
        value:'jakarta',
        name:'Джакарта',
    },
    {
        id:55,
        value:'kiev',
        name:'Киев',
    },
    {
        id:56,
        value:'copenhagen ',
        name:'Копенгаген',
    },
    {
        id:57,
        value:'kuala-lumpur',
        name:'Куала-Лумпур',
    },
    {
        id:58,
        value:'london',
        name:'Лондон',
    },
    {
        id:59,
        value:'madrid',
        name:'Мадрид',
    },
    {
        id:60,
        value:'mexico',
        name:'Мехико',
    },
    {
        id:61,
        value:'minsk',
        name:'Минск',
    },
    {
        id:62,
        value:'moscow',
        name:'Москва',
    },
    {
        id:63,
        value:'astana',
        name:'Нур-Султан (Астана)',
    },
    {
        id:64,
        value:'oslo',
        name:'Осло',
    },
    {
        id:65,
        value:'ottava',
        name:'Оттава',
    },
    {
        id:66,
        value:'paris',
        name:'Париж',
    },
    {
        id:67,
        value:'praga',
        name:'Прага',
    },
    {
        id:68,
        value:'riga',
        name:'Рига',
    },
    {
        id:69,
        value:'rome',
        name:'Рим',
    },
    {
        id:70,
        value:'seul',
        name:'Сеул',
    },
    {
        id:71,
        value:'singapore',
        name:'Сингапур',
    },
    {
        id:72,
        value:'tallin',
        name:'Таллинн',
    },
    {
        id:73,
        value:'Tehran ',
        name:'Тегеран',
    },
    {
        id:74,
        value:'tokyo',
        name:'Токио',
    },
    {
        id:75,
        value:'khelsinki',
        name:'Хельсинки',
    },
    {
        id:76,
        value:'kuweit',
        name:'Эль-Кувейт',
    },
    {
        id:77,
        value:'riyad',
        name:'Эр-Рияд',
    },
    {
        id:78,
        value:'нamoussoukro',
        name:'Ямусукро',
    }
]